### ISSUE TITLE
does not work with vs code 1.45.1

### ISSUE THREAD

**Issue by insinfo** [aadarshadhakalg/ADSnippets#8]
first congratulations on the work, I love AngularDart, and I'm happy to see people working to make AngularDart development better, I tried to install this extension on my vs code and couldn't, I would like to know if you have any predictions to support an intellisense too (Some auto complete) in the angular template, since the angular analysis plugin is no longer working

![image](https://user-images.githubusercontent.com/12227024/115926092-a0654200-a458-11eb-91c9-fc394871e504.png)

**Comment by insinfo** [comment]
Maybe that can help

https://github.com/dart-lang/sdk/blob/master/pkg/analyzer_plugin/doc/tutorial/tutorial.md
https://github.com/Thiltal/angular_analyzer_plugin_example
https://chromium.googlesource.com/external/github.com/dart-lang/angular_analyzer_plugin/+/refs/heads/for-paul/angular_analyzer_plugin/
https://chromium.googlesource.com/external/github.com/dart-lang/angular_analyzer_plugin/+archive/refs/heads/for-paul/angular_analyzer_plugin.tar.gz

**Comment by aadarshadhakalg** [comment]
@insinfo  good to see you are happy with this project. I have no plans about how to make this better or add some auto-completion features for now. 

A year back I was trying to learn a frontend framework and since I was a little bit familiar with dart language I decided to learn angular dart. While doing the angular dart project I found that some codes I need to use repeatedly. So to make my work easy I created this extension that provides few snippets. Later @lejard-h  contributed some amazing improvements.

I do love Andular Dart (I was enjoying using it those days ) and it's a very sad thing to see everything falling apart. This project has remained untouched for the last 5-6 months. So I would be very happy if someone can take responsibility for project. And yeah thank you for being here!

**Comment by lejard-h** [comment]
Hi @insinfo 

It seems that you are using an old version of VsCode ( 1 year ago)
It works fine with the last version `1.55.2`, I recommend you to upgrade your VsCode. I don't think we will support old version like that.

**Comment by lejard-h** [comment]
About autocompletion, It's indeed something I wanted to do. But it's not easy to me since I don't have a lot of experience in VsCode extension, Dart analyzer and Dart Language Server. I still want to do it but don't have much time and don't know were to start, maybe @DanTup can orient me about that (resources, DartCode extension example ... :pray: ) 

I could also fork `angular_analyzer_plugin` but I need more info about why it has been deprecated (/cc @kevmoo, @lukaszkolodziejczyk)

I will open new issue so we can continue the discussion
